#!/bin/bash

if [ -f .env ]; then
    export $(cat .env | grep -v '#' | awk '/=/ {print $1}')
    ssh -t "$SSH_USER@$SSH_HOST" 'sudo git config --global --add safe.directory /home/immoplus-api-v2/htdocs/api-immoplus-v2 && cd /home/immoplus-api-v2/htdocs/api-immoplus-v2 && sudo sh redeploy'
fi


