#!/bin/bash

if [ -f .env ]; then
    export $(cat .env | grep -v '#' | awk '/=/ {print $1}')
    ssh -t "$SSH_USER@$SSH_HOST" 'cd /home/immoplus-api-v2/htdocs/api-v2.immoplus.c && sudo sh redeploy'
fi