#!/bin/bash

if [ -f .env ]; then
    export $(cat .env | grep -v '#' | awk '/=/ {print $1}')
    sudo docker run -ti -v "$(pwd)":/apps -w /apps alpine/bruno run --env=local $1
#    sudo docker run -ti --rm -v "$(pwd)":/apps -w /apps alpine/bruno run --env=sandbox
fi


