version: '3.4'
services:
  api:
    container_name: ${NEST_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '${NEST_PORT}:8055'
    volumes:
      - ${NEST_UPLOAD_DIR}:/app/uploads
    env_file:
      - ./.env
    environment:
      PORT: 8055
