version: '3.4'
services:

  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '${NEST_PORT}:3000'
    volumes:
      - ${NEST_UPLOAD_DIR}:/app/uploads
    env_file:
      - ./.env


