version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: ${JENKINS_CONTAINER_NAME}
    restart: always
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT}:8080
      - ${JENKINS_PORT_2}:50000
    volumes:
      - ${JENKINS_HOME_PATH}:/var/jenkins_home
      - ${JENKINS_HOME_PATH}/workspace:/var/jenkins_home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker

  dockge:
    image: louislam/dockge:1
    restart: always
    container_name: ${DOCKGE_CONTAINER_NAME}
    ports:
      - ${DOCKGE_PORT}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKGE_PATH}:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true
