version: '3.9'
services:

  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - ${NEST_PORT}:3000
    volumes:
      - nestjs_uploads:/app/uploads
    env_file:
      - ./.env

volumes:
  nestjs_uploads:


