#!/bin/bash

if [ -f .env ]; then
    export $(cat .env | grep -v '#' | awk '/=/ {print $1}')
    sudo docker run -d --mount type=bind,source=./mockoon.json,target=/data,readonly -p 3003:3003 mockoon/cli:latest --data data --port 3003
fi

